#!/usr/bin/bash
export PROJECT_ROOT=$PWD
export PROJECT_NAME=$(basename "$PROJECT_ROOT")
export PATH=$PROJECT_ROOT/scripts/bin:$PATH
export PYTHONPATH=$(pwd)
export COCOTB_SIM=1
source $PROJECT_ROOT/_env/bin/activate
